-- Generated from Odin's authoritative Kanto species catalog.
-- Do not edit by hand; run tools/generate_kanto_bestiary.js.
return {
  [10001] = { id = 1, name = "Bulbasaur", lookType = 3001, types = { "grass", "poison" }, habitats = { "forests", "routes" } },
  [10002] = { id = 2, name = "Ivysaur", lookType = 3002, types = { "grass", "poison" }, habitats = { "forests", "routes" } },
  [10003] = { id = 3, name = "Venusaur", lookType = 3003, types = { "grass", "poison" }, habitats = { "forests", "routes" } },
  [10004] = { id = 4, name = "Charmander", lookType = 3004, types = { "fire" }, habitats = { "routes" } },
  [10005] = { id = 5, name = "Charmeleon", lookType = 3005, types = { "fire" }, habitats = { "routes" } },
  [10006] = { id = 6, name = "Charizard", lookType = 3006, types = { "fire", "flying" }, habitats = { "routes" } },
  [10007] = { id = 7, name = "Squirtle", lookType = 3007, types = { "water" }, habitats = { "waters" } },
  [10008] = { id = 8, name = "Wartortle", lookType = 3008, types = { "water" }, habitats = { "waters" } },
  [10009] = { id = 9, name = "Blastoise", lookType = 3009, types = { "water" }, habitats = { "waters" } },
  [10010] = { id = 10, name = "Caterpie", lookType = 3010, types = { "bug" }, habitats = { "forests" } },
  [10011] = { id = 11, name = "Metapod", lookType = 3011, types = { "bug" }, habitats = { "forests" } },
  [10012] = { id = 12, name = "Butterfree", lookType = 3012, types = { "bug", "flying" }, habitats = { "forests", "routes" } },
  [10013] = { id = 13, name = "Weedle", lookType = 3013, types = { "bug", "poison" }, habitats = { "forests", "routes" } },
  [10014] = { id = 14, name = "Kakuna", lookType = 3014, types = { "bug", "poison" }, habitats = { "forests", "routes" } },
  [10015] = { id = 15, name = "Beedrill", lookType = 3015, types = { "bug", "poison" }, habitats = { "forests", "routes" } },
  [10016] = { id = 16, name = "Pidgey", lookType = 3016, types = { "normal", "flying" }, habitats = { "routes" } },
  [10017] = { id = 17, name = "Pidgeotto", lookType = 3017, types = { "normal", "flying" }, habitats = { "routes" } },
  [10018] = { id = 18, name = "Pidgeot", lookType = 3018, types = { "normal", "flying" }, habitats = { "routes" } },
  [10019] = { id = 19, name = "Rattata", lookType = 3019, types = { "normal" }, habitats = { "routes" } },
  [10020] = { id = 20, name = "Raticate", lookType = 3020, types = { "normal" }, habitats = { "routes" } },
  [10021] = { id = 21, name = "Spearow", lookType = 3021, types = { "normal", "flying" }, habitats = { "routes" } },
  [10022] = { id = 22, name = "Fearow", lookType = 3022, types = { "normal", "flying" }, habitats = { "routes" } },
  [10023] = { id = 23, name = "Ekans", lookType = 3023, types = { "poison" }, habitats = { "routes" } },
  [10024] = { id = 24, name = "Arbok", lookType = 3024, types = { "poison" }, habitats = { "routes" } },
  [10025] = { id = 25, name = "Pikachu", lookType = 3025, types = { "electric" }, habitats = { "power_plant" } },
  [10026] = { id = 26, name = "Raichu", lookType = 3026, types = { "electric" }, habitats = { "power_plant" } },
  [10027] = { id = 27, name = "Sandshrew", lookType = 3027, types = { "ground" }, habitats = { "caves", "mountains" } },
  [10028] = { id = 28, name = "Sandslash", lookType = 3028, types = { "ground" }, habitats = { "caves", "mountains" } },
  [10029] = { id = 29, name = "Nidoran F", lookType = 3029, types = { "poison" }, habitats = { "routes", "safari_zone" } },
  [10030] = { id = 30, name = "Nidorina", lookType = 3030, types = { "poison" }, habitats = { "routes", "safari_zone" } },
  [10031] = { id = 31, name = "Nidoqueen", lookType = 3031, types = { "poison", "ground" }, habitats = { "caves", "mountains", "routes", "safari_zone" } },
  [10032] = { id = 32, name = "Nidoran M", lookType = 3032, types = { "poison" }, habitats = { "routes", "safari_zone" } },
  [10033] = { id = 33, name = "Nidorino", lookType = 3033, types = { "poison" }, habitats = { "routes", "safari_zone" } },
  [10034] = { id = 34, name = "Nidoking", lookType = 3034, types = { "poison", "ground" }, habitats = { "caves", "mountains", "routes", "safari_zone" } },
  [10035] = { id = 35, name = "Clefairy", lookType = 3035, types = { "fairy" }, habitats = { "routes" } },
  [10036] = { id = 36, name = "Clefable", lookType = 3036, types = { "fairy" }, habitats = { "routes" } },
  [10037] = { id = 37, name = "Vulpix", lookType = 3037, types = { "fire" }, habitats = { "routes" } },
  [10038] = { id = 38, name = "Ninetales", lookType = 3038, types = { "fire" }, habitats = { "routes" } },
  [10039] = { id = 39, name = "Jigglypuff", lookType = 3039, types = { "normal", "fairy" }, habitats = { "routes" } },
  [10040] = { id = 40, name = "Wigglytuff", lookType = 3040, types = { "normal", "fairy" }, habitats = { "routes" } },
  [10041] = { id = 41, name = "Zubat", lookType = 3041, types = { "poison", "flying" }, habitats = { "routes" } },
  [10042] = { id = 42, name = "Golbat", lookType = 3042, types = { "poison", "flying" }, habitats = { "routes" } },
  [10043] = { id = 43, name = "Oddish", lookType = 3043, types = { "grass", "poison" }, habitats = { "forests", "routes" } },
  [10044] = { id = 44, name = "Gloom", lookType = 3044, types = { "grass", "poison" }, habitats = { "forests", "routes" } },
  [10045] = { id = 45, name = "Vileplume", lookType = 3045, types = { "grass", "poison" }, habitats = { "forests", "routes" } },
  [10046] = { id = 46, name = "Paras", lookType = 3046, types = { "bug", "grass" }, habitats = { "forests", "safari_zone" } },
  [10047] = { id = 47, name = "Parasect", lookType = 3047, types = { "bug", "grass" }, habitats = { "forests", "safari_zone" } },
  [10048] = { id = 48, name = "Venonat", lookType = 3048, types = { "bug", "poison" }, habitats = { "forests", "routes", "safari_zone" } },
  [10049] = { id = 49, name = "Venomoth", lookType = 3049, types = { "bug", "poison" }, habitats = { "forests", "routes", "safari_zone" } },
  [10050] = { id = 50, name = "Diglett", lookType = 3050, types = { "ground" }, habitats = { "caves", "mountains" } },
  [10051] = { id = 51, name = "Dugtrio", lookType = 3051, types = { "ground" }, habitats = { "caves", "mountains" } },
  [10052] = { id = 52, name = "Meowth", lookType = 3052, types = { "normal" }, habitats = { "routes" } },
  [10053] = { id = 53, name = "Persian", lookType = 3053, types = { "normal" }, habitats = { "routes" } },
  [10054] = { id = 54, name = "Psyduck", lookType = 3054, types = { "water" }, habitats = { "waters" } },
  [10055] = { id = 55, name = "Golduck", lookType = 3055, types = { "water" }, habitats = { "waters" } },
  [10056] = { id = 56, name = "Mankey", lookType = 3056, types = { "fighting" }, habitats = { "routes" } },
  [10057] = { id = 57, name = "Primeape", lookType = 3057, types = { "fighting" }, habitats = { "routes" } },
  [10058] = { id = 58, name = "Growlithe", lookType = 3058, types = { "fire" }, habitats = { "routes" } },
  [10059] = { id = 59, name = "Arcanine", lookType = 3059, types = { "fire" }, habitats = { "routes" } },
  [10060] = { id = 60, name = "Poliwag", lookType = 3060, types = { "water" }, habitats = { "waters" } },
  [10061] = { id = 61, name = "Poliwhirl", lookType = 3061, types = { "water" }, habitats = { "waters" } },
  [10062] = { id = 62, name = "Poliwrath", lookType = 3062, types = { "water", "fighting" }, habitats = { "waters" } },
  [10063] = { id = 63, name = "Abra", lookType = 3063, types = { "psychic" }, habitats = { "routes" } },
  [10064] = { id = 64, name = "Kadabra", lookType = 3064, types = { "psychic" }, habitats = { "routes" } },
  [10065] = { id = 65, name = "Alakazam", lookType = 3065, types = { "psychic" }, habitats = { "routes" } },
  [10066] = { id = 66, name = "Machop", lookType = 3066, types = { "fighting" }, habitats = { "routes" } },
  [10067] = { id = 67, name = "Machoke", lookType = 3067, types = { "fighting" }, habitats = { "routes" } },
  [10068] = { id = 68, name = "Machamp", lookType = 3068, types = { "fighting" }, habitats = { "routes" } },
  [10069] = { id = 69, name = "Bellsprout", lookType = 3069, types = { "grass", "poison" }, habitats = { "forests", "routes" } },
  [10070] = { id = 70, name = "Weepinbell", lookType = 3070, types = { "grass", "poison" }, habitats = { "forests", "routes" } },
  [10071] = { id = 71, name = "Victreebel", lookType = 3071, types = { "grass", "poison" }, habitats = { "forests", "routes" } },
  [10072] = { id = 72, name = "Tentacool", lookType = 3072, types = { "water", "poison" }, habitats = { "waters", "routes" } },
  [10073] = { id = 73, name = "Tentacruel", lookType = 3073, types = { "water", "poison" }, habitats = { "waters", "routes" } },
  [10074] = { id = 74, name = "Geodude", lookType = 3074, types = { "rock", "ground" }, habitats = { "caves", "mountains" } },
  [10075] = { id = 75, name = "Graveler", lookType = 3075, types = { "rock", "ground" }, habitats = { "caves", "mountains" } },
  [10076] = { id = 76, name = "Golem", lookType = 3076, types = { "rock", "ground" }, habitats = { "caves", "mountains" } },
  [10077] = { id = 77, name = "Ponyta", lookType = 3077, types = { "fire" }, habitats = { "routes" } },
  [10078] = { id = 78, name = "Rapidash", lookType = 3078, types = { "fire" }, habitats = { "routes" } },
  [10079] = { id = 79, name = "Slowpoke", lookType = 3079, types = { "water", "psychic" }, habitats = { "waters" } },
  [10080] = { id = 80, name = "Slowbro", lookType = 3080, types = { "water", "psychic" }, habitats = { "waters" } },
  [10081] = { id = 81, name = "Magnemite", lookType = 3081, types = { "electric", "steel" }, habitats = { "power_plant" } },
  [10082] = { id = 82, name = "Magneton", lookType = 3082, types = { "electric", "steel" }, habitats = { "power_plant" } },
  [10083] = { id = 83, name = "Farfetchd", lookType = 3083, types = { "normal", "flying" }, habitats = { "routes" } },
  [10084] = { id = 84, name = "Doduo", lookType = 3084, types = { "normal", "flying" }, habitats = { "routes" } },
  [10085] = { id = 85, name = "Dodrio", lookType = 3085, types = { "normal", "flying" }, habitats = { "routes" } },
  [10086] = { id = 86, name = "Seel", lookType = 3086, types = { "water" }, habitats = { "waters" } },
  [10087] = { id = 87, name = "Dewgong", lookType = 3087, types = { "water", "ice" }, habitats = { "waters" } },
  [10088] = { id = 88, name = "Grimer", lookType = 3088, types = { "poison" }, habitats = { "routes" } },
  [10089] = { id = 89, name = "Muk", lookType = 3089, types = { "poison" }, habitats = { "routes" } },
  [10090] = { id = 90, name = "Shellder", lookType = 3090, types = { "water" }, habitats = { "waters" } },
  [10091] = { id = 91, name = "Cloyster", lookType = 3091, types = { "water", "ice" }, habitats = { "waters" } },
  [10092] = { id = 92, name = "Gastly", lookType = 3092, types = { "ghost", "poison" }, habitats = { "routes", "pokemon_tower" } },
  [10093] = { id = 93, name = "Haunter", lookType = 3093, types = { "ghost", "poison" }, habitats = { "routes", "pokemon_tower" } },
  [10094] = { id = 94, name = "Gengar", lookType = 3094, types = { "ghost", "poison" }, habitats = { "routes", "pokemon_tower" } },
  [10095] = { id = 95, name = "Onix", lookType = 3095, types = { "rock", "ground" }, habitats = { "caves", "mountains" } },
  [10096] = { id = 96, name = "Drowzee", lookType = 3096, types = { "psychic" }, habitats = { "routes" } },
  [10097] = { id = 97, name = "Hypno", lookType = 3097, types = { "psychic" }, habitats = { "routes" } },
  [10098] = { id = 98, name = "Krabby", lookType = 3098, types = { "water" }, habitats = { "waters" } },
  [10099] = { id = 99, name = "Kingler", lookType = 3099, types = { "water" }, habitats = { "waters" } },
  [10100] = { id = 100, name = "Voltorb", lookType = 3100, types = { "electric" }, habitats = { "power_plant" } },
  [10101] = { id = 101, name = "Electrode", lookType = 3101, types = { "electric" }, habitats = { "power_plant" } },
  [10102] = { id = 102, name = "Exeggcute", lookType = 3102, types = { "grass", "psychic" }, habitats = { "forests", "safari_zone" } },
  [10103] = { id = 103, name = "Exeggutor", lookType = 3103, types = { "grass", "psychic" }, habitats = { "forests", "safari_zone" } },
  [10104] = { id = 104, name = "Cubone", lookType = 3104, types = { "ground" }, habitats = { "caves", "mountains", "pokemon_tower" } },
  [10105] = { id = 105, name = "Marowak", lookType = 3105, types = { "ground" }, habitats = { "caves", "mountains", "pokemon_tower" } },
  [10106] = { id = 106, name = "Hitmonlee", lookType = 3106, types = { "fighting" }, habitats = { "routes" } },
  [10107] = { id = 107, name = "Hitmonchan", lookType = 3107, types = { "fighting" }, habitats = { "routes" } },
  [10108] = { id = 108, name = "Lickitung", lookType = 3108, types = { "normal" }, habitats = { "routes" } },
  [10109] = { id = 109, name = "Koffing", lookType = 3109, types = { "poison" }, habitats = { "routes" } },
  [10110] = { id = 110, name = "Weezing", lookType = 3110, types = { "poison" }, habitats = { "routes" } },
  [10111] = { id = 111, name = "Rhyhorn", lookType = 3111, types = { "ground", "rock" }, habitats = { "caves", "mountains", "safari_zone" } },
  [10112] = { id = 112, name = "Rhydon", lookType = 3112, types = { "ground", "rock" }, habitats = { "caves", "mountains", "safari_zone" } },
  [10113] = { id = 113, name = "Chansey", lookType = 3113, types = { "normal" }, habitats = { "routes", "safari_zone" } },
  [10114] = { id = 114, name = "Tangela", lookType = 3114, types = { "grass" }, habitats = { "forests" } },
  [10115] = { id = 115, name = "Kangaskhan", lookType = 3115, types = { "normal" }, habitats = { "routes", "safari_zone" } },
  [10116] = { id = 116, name = "Horsea", lookType = 3116, types = { "water" }, habitats = { "waters" } },
  [10117] = { id = 117, name = "Seadra", lookType = 3117, types = { "water" }, habitats = { "waters" } },
  [10118] = { id = 118, name = "Goldeen", lookType = 3118, types = { "water" }, habitats = { "waters" } },
  [10119] = { id = 119, name = "Seaking", lookType = 3119, types = { "water" }, habitats = { "waters" } },
  [10120] = { id = 120, name = "Staryu", lookType = 3120, types = { "water" }, habitats = { "waters" } },
  [10121] = { id = 121, name = "Starmie", lookType = 3121, types = { "water", "psychic" }, habitats = { "waters" } },
  [10122] = { id = 122, name = "Mr Mime", lookType = 3122, types = { "psychic", "fairy" }, habitats = { "routes" } },
  [10123] = { id = 123, name = "Scyther", lookType = 3123, types = { "bug", "flying" }, habitats = { "forests", "routes", "safari_zone" } },
  [10124] = { id = 124, name = "Jynx", lookType = 3124, types = { "ice", "psychic" }, habitats = { "routes" } },
  [10125] = { id = 125, name = "Electabuzz", lookType = 3125, types = { "electric" }, habitats = { "power_plant" } },
  [10126] = { id = 126, name = "Magmar", lookType = 3126, types = { "fire" }, habitats = { "routes" } },
  [10127] = { id = 127, name = "Pinsir", lookType = 3127, types = { "bug" }, habitats = { "forests", "safari_zone" } },
  [10128] = { id = 128, name = "Tauros", lookType = 3128, types = { "normal" }, habitats = { "routes", "safari_zone" } },
  [10129] = { id = 129, name = "Magikarp", lookType = 3129, types = { "water" }, habitats = { "waters" } },
  [10130] = { id = 130, name = "Gyarados", lookType = 3130, types = { "water", "flying" }, habitats = { "waters", "routes" } },
  [10131] = { id = 131, name = "Lapras", lookType = 3131, types = { "water", "ice" }, habitats = { "waters" } },
  [10132] = { id = 132, name = "Ditto", lookType = 3132, types = { "normal" }, habitats = { "routes" } },
  [10133] = { id = 133, name = "Eevee", lookType = 3133, types = { "normal" }, habitats = { "routes" } },
  [10134] = { id = 134, name = "Vaporeon", lookType = 3134, types = { "water" }, habitats = { "waters" } },
  [10135] = { id = 135, name = "Jolteon", lookType = 3135, types = { "electric" }, habitats = { "routes" } },
  [10136] = { id = 136, name = "Flareon", lookType = 3136, types = { "fire" }, habitats = { "routes" } },
  [10137] = { id = 137, name = "Porygon", lookType = 3137, types = { "normal" }, habitats = { "routes" } },
  [10138] = { id = 138, name = "Omanyte", lookType = 3138, types = { "rock", "water" }, habitats = { "waters", "caves", "mountains" } },
  [10139] = { id = 139, name = "Omastar", lookType = 3139, types = { "rock", "water" }, habitats = { "waters", "caves", "mountains" } },
  [10140] = { id = 140, name = "Kabuto", lookType = 3140, types = { "rock", "water" }, habitats = { "waters", "caves", "mountains" } },
  [10141] = { id = 141, name = "Kabutops", lookType = 3141, types = { "rock", "water" }, habitats = { "waters", "caves", "mountains" } },
  [10142] = { id = 142, name = "Aerodactyl", lookType = 3142, types = { "rock", "flying" }, habitats = { "caves", "mountains", "routes" } },
  [10143] = { id = 143, name = "Snorlax", lookType = 3143, types = { "normal" }, habitats = { "routes" } },
  [10144] = { id = 144, name = "Articuno", lookType = 3144, types = { "ice", "flying" }, habitats = { "routes", "legendary" } },
  [10145] = { id = 145, name = "Zapdos", lookType = 3145, types = { "electric", "flying" }, habitats = { "routes", "power_plant", "legendary" } },
  [10146] = { id = 146, name = "Moltres", lookType = 3146, types = { "fire", "flying" }, habitats = { "routes", "legendary" } },
  [10147] = { id = 147, name = "Dratini", lookType = 3147, types = { "dragon" }, habitats = { "routes" } },
  [10148] = { id = 148, name = "Dragonair", lookType = 3148, types = { "dragon" }, habitats = { "routes" } },
  [10149] = { id = 149, name = "Dragonite", lookType = 3149, types = { "dragon", "flying" }, habitats = { "routes" } },
  [10150] = { id = 150, name = "Mewtwo", lookType = 3150, types = { "psychic" }, habitats = { "legendary" } },
  [10151] = { id = 151, name = "Mew", lookType = 3151, types = { "psychic" }, habitats = { "legendary" } },
}
