Pokemon = Pokemon or {}

dofile(DATA_DIRECTORY .. "/lib/pokemon/constants.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/rules.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/combat_config.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/types.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/equipment.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/balls.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/corpses.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/natures.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/stats.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/species.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/encounter.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/progression.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/instance.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/evolution.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/moves.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/capture.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/capture_bag.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/repository.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/team.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/summon.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/target_policy.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/battle_lock.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/move_casting.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/roster_protocol.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/healing.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/nurse_joy_interaction.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/travel.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/monster_factory.lua")

PokemonSpecies.loadCatalog()
